language: cpp
dist: xenial
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt592-xenial -y
  - sudo apt-get update

install:
  - sudo apt-get install qt59base qt59svg qt58charts-no-lgpl qt59xmlpatterns qt59webengine
  - source /opt/qt58/bin/qt58-env.sh


script:
  - /opt/qt58/bin/qmake PREFIX=/usr
  - make
