language: cpp
dist: xenial
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt592-xenial -y
  - sudo apt-get update

install:
  - sudo apt-get install libglu1-mesa-dev qt59base qt59svg qt59xmlpatterns qt59webengine
  - source /opt/qt59/bin/qt59-env.sh


script:
  - /opt/qt59/bin/qmake PREFIX=/usr
  - make
